" Basic configurations
set hls
set nu
set is
set ruler
set showcmd
set tabstop=4
set shiftwidth=4
set expandtab
set laststatus=2
set cursorline
set noshowmode
set nowrap
set title
set nowrapscan

" Select Visual Code style color scheme (codedark)
colorscheme codedark

" Remappings

" Highlight trailing spaces

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

"Show a mark when passing an specified column (80 in my case)

highlight ColorColumn ctermbg=DarkCyan
call matchadd('ColorColumn', '\%81v', 100)

" Clear highlighting on escape in normal mode

nnoremap <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[

" Always open help command in vertical

augroup vimrc_help
  autocmd!
  autocmd BufEnter *.txt if &buftype == 'help' | wincmd L | endif
augroup END

" Provides vim access to all archives inside the project
" getting a more complete tab-completion

set path+=**

" Display all matching files when we tab complete

set wildmenu

" Netrw Configurations

let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=0  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view

" Snippets
nnoremap _sig :-1read $HOME/.vim/snippets/programming_signature<CR>
